name: Test Codebase

on: [push, pull_request]

jobs:
  test:
    name: Test on NodeJS v12
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 12.x, 14.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Test using Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm test
